- name: Variables from play level
  hosts: localhost
  vars: 
    Course: "DevOps"
    Trainer: "Mani"
    Duration: "120HRS"
  tasks:
  - name: check variables
    vars: #task level
      Course: "DevOps with AWS"
    ansible.builtin.debug:
      msg: "Hi I am learni {{Course}}, Trainer is {{Trainer}}, Duration is {{Duration}}"
      