- name: Variables from play level
  hosts: localhost
  vars_files:
  - variables.yaml
  tasks:
  - name: check variables
    vars: #task level
      Course: "DevOps with AWS"
    ansible.builtin.debug:
      msg: "Hi I am learni {{Course}}, Trainer is {{Trainer}}, Duration is {{Duration}}"
      