- name: variables from PLAY level
  hosts: localhost
  tasks: 
  - name: check variables
    ansible.builtin.debug:
     msg: " Hi i am learnig {{Course}}, Trainer is {{Trainer}}, Duration is {{Duration}}"