- name: checking data types
  hosts: localhost
  vars:
    NAME: "Mani"  # key-value
    SKILLS:       # list type
      - DevOps
      - Linux
      - Docker
      - Shell
    Experience:   # map type
      DevOps: 7
      AWS: 9
      Docker: 8
    Trainer: true # boolean

  tasks:
    - name: print key value pair
      ansible.builtin.debug:
        msg: "Name: {{ NAME }}"

    - name: print list
      ansible.builtin.debug:
        msg: "Skills: {{ SKILLS }}"

    - name: print map
      ansible.builtin.debug:
        msg: "Experience: {{ Experience }}"

    - name: print boolean
      ansible.builtin.debug:
        msg: "Is he Trainer: {{ Trainer }}"

  